name: ci

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 8 * * 1-5'
  workflow_dispatch:

jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        python: [3.13]
        aiida: [2.9.0, 2.9.1]
        gromacs: [2026.3]
        plumed: [2.10.1]
    continue-on-error: false
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    container:
        image: ghcr.io/mamba-org/micromamba:2.9.0-ubuntu24.04
        options: --user=root # required for checkout to mount
    name: py${{ matrix.python }}-aiida${{ matrix.aiida }}
    defaults:
      run:
        shell: _entrypoint.sh /bin/bash --noprofile --norc -eo pipefail {0}
    steps:
    - name: checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Add mamba and pip packages
      run: |
        micromamba create -n testing -c conda-forge python=${{ matrix.python }} aiida-core=${{ matrix.aiida }} gromacs=${{ matrix.gromacs }}=nompi_* plumed=${{ matrix.plumed }}=mpi_nompi_*
        micromamba activate testing
        echo "PLUMED_KERNEL=/opt/conda/lib/libplumedKernel.so" >> "$GITHUB_ENV"
        pip install -e .[testing]

    - name: Run test suite
      run: |
        micromamba activate testing
        pytest -s --cov aiida_gromacs --cov-report term-missing --cov-append .

    - name: Report Coverage
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
      with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true

  finish:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
      with:
        parallel-finished: true

  docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up Python 3.13
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.13

    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[docs]

    - name: Build docs
      run: cd docs && make

  pre-commit:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up Python 3.13
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.13

    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[pre-commit]

    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
